name: flutter_order_tv
description: 订单展示TV项目.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mp3/开启语音.mp3
